"use client";
import {useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
export default function Home(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[username,setUsername]=useState(""),[signup,setSignup]=useState(false),[age,setAge]=useState(false),[msg,setMsg]=useState(""),[rooms,setRooms]=useState([]),[room,setRoom]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(""),[names,setNames]=useState({});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data}=await supabase.from("rooms").select("*").order("id");setRooms(data||[]);if(data?.[0])setRoom(data[0])}
 useEffect(()=>{if(!room||!session)return;loadMessages();const ch=supabase.channel("room"+room.id).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`room_id=eq.${room.id}`},p=>setMessages(x=>[...x,p.new])).subscribe();return()=>supabase.removeChannel(ch)},[room,session]);
 async function loadMessages(){const {data}=await supabase.from("messages").select("*").eq("room_id",room.id).order("created_at");setMessages(data||[]);const ids=[...new Set((data||[]).map(x=>x.user_id))];if(ids.length){const {data:p}=await supabase.from("profiles").select("id,username").in("id",ids);setNames(Object.fromEntries((p||[]).map(x=>[x.id,x.username])))}} 
 async function auth(e){e.preventDefault();setMsg("");if(signup){if(!age)return setMsg("Please confirm the age requirement.");const r=await supabase.auth.signUp({email,password,options:{data:{username}}});if(r.error)return setMsg(r.error.message);setMsg(r.data.session?"":"Check your email if confirmation is required.");}else{const r=await supabase.auth.signInWithPassword({email,password});if(r.error)setMsg(r.error.message)}}
 async function send(e){e.preventDefault();if(!text.trim())return;const r=await supabase.from("messages").insert({room_id:room.id,user_id:session.user.id,content:text.trim()});if(r.error)setMsg(r.error.message);else setText("")}
 if(!session)return <main className="auth"><div className="card"><div className="logo">A<span>•</span></div><h1>TeenChatSpace</h1><p>Chat, meet people, share interests.</p><form onSubmit={auth}>{signup&&<input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/>{signup&&<label><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)}/> I meet the site's minimum age requirement.</label>}{msg&&<small>{msg}</small>}<button>{signup?"Create account":"Log in"}</button></form><a onClick={()=>setSignup(!signup)}>{signup?"I already have an account":"Create an account"}</a></div></main>;
 return <main><header><b>TeenChatSpace</b><button onClick={()=>supabase.auth.signOut()}>Log out</button></header><div className="rooms">{rooms.map(r=><button className={room?.id===r.id?"active":""} onClick={()=>setRoom(r)} key={r.id}># {r.name}</button>)}</div><section className="chat"><h3>#{room?.name}</h3><div className="messages">{messages.map(m=><div className={m.user_id===session.user.id?"mine":"bubble"} key={m.id}><b>{names[m.user_id]||"User"}</b><br/>{m.content}</div>)}</div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…"/><button>➤</button></form></section></main>
}
